# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nvidia/workspace/Pong_final

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nvidia/workspace/Pong_final/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nvidia/workspace/Pong_final/build/CMakeFiles /home/nvidia/workspace/Pong_final/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nvidia/workspace/Pong_final/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Pong_final_proj

# Build rule for target.
Pong_final_proj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Pong_final_proj
.PHONY : Pong_final_proj

# fast build rule for target.
Pong_final_proj/fast:
	$(MAKE) -f CMakeFiles/Pong_final_proj.dir/build.make CMakeFiles/Pong_final_proj.dir/build
.PHONY : Pong_final_proj/fast

Pong_final.o: Pong_final.cpp.o

.PHONY : Pong_final.o

# target to build an object file
Pong_final.cpp.o:
	$(MAKE) -f CMakeFiles/Pong_final_proj.dir/build.make CMakeFiles/Pong_final_proj.dir/Pong_final.cpp.o
.PHONY : Pong_final.cpp.o

Pong_final.i: Pong_final.cpp.i

.PHONY : Pong_final.i

# target to preprocess a source file
Pong_final.cpp.i:
	$(MAKE) -f CMakeFiles/Pong_final_proj.dir/build.make CMakeFiles/Pong_final_proj.dir/Pong_final.cpp.i
.PHONY : Pong_final.cpp.i

Pong_final.s: Pong_final.cpp.s

.PHONY : Pong_final.s

# target to generate assembly for a file
Pong_final.cpp.s:
	$(MAKE) -f CMakeFiles/Pong_final_proj.dir/build.make CMakeFiles/Pong_final_proj.dir/Pong_final.cpp.s
.PHONY : Pong_final.cpp.s

leastSquare.o: leastSquare.cpp.o

.PHONY : leastSquare.o

# target to build an object file
leastSquare.cpp.o:
	$(MAKE) -f CMakeFiles/Pong_final_proj.dir/build.make CMakeFiles/Pong_final_proj.dir/leastSquare.cpp.o
.PHONY : leastSquare.cpp.o

leastSquare.i: leastSquare.cpp.i

.PHONY : leastSquare.i

# target to preprocess a source file
leastSquare.cpp.i:
	$(MAKE) -f CMakeFiles/Pong_final_proj.dir/build.make CMakeFiles/Pong_final_proj.dir/leastSquare.cpp.i
.PHONY : leastSquare.cpp.i

leastSquare.s: leastSquare.cpp.s

.PHONY : leastSquare.s

# target to generate assembly for a file
leastSquare.cpp.s:
	$(MAKE) -f CMakeFiles/Pong_final_proj.dir/build.make CMakeFiles/Pong_final_proj.dir/leastSquare.cpp.s
.PHONY : leastSquare.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Pong_final_proj"
	@echo "... Pong_final.o"
	@echo "... Pong_final.i"
	@echo "... Pong_final.s"
	@echo "... leastSquare.o"
	@echo "... leastSquare.i"
	@echo "... leastSquare.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

